services:
  oathkeeper:
    image: oryd/oathkeeper:v0.40
    depends_on:
      - kratos-selfservice-ui-node
    ports:
      - 4455:4455 # proxy
      - 4456:4456 # api
    command:
      serve proxy -c "/etc/config/oathkeeper/oathkeeper.yml"
    environment:
      - LOG_LEVEL=debug
    restart: on-failure
    networks:
      - intranet
    volumes:
      - ./oathkeeper:/etc/config/oathkeeper

  kratos-selfservice-ui-node:
    image: oryd/kratos-selfservice-ui-node:v1.1.0
    depends_on:
      - kratos
    environment:
      - PORT=4435
      - KRATOS_PUBLIC_URL=http://kratos:4433/
      - KRATOS_BROWSER_URL=http://127.0.0.1:4455/.ory/kratos/public
      - JWKS_URL=http://oathkeeper:4456/.well-known/jwks.json
      - SECURITY_MODE=jwks
      - COOKIE_SECRET=changeme
      - CSRF_COOKIE_NAME=ory_csrf_ui
      - CSRF_COOKIE_SECRET=changeme
    networks:
      - intranet
    restart: on-failure

  kratos-migrate:
    image: oryd/kratos:v1.1.0
    depends_on:
      - cockroachdb
    environment:
      - DSN=cockroach://root@cockroachdb:26257/defaultdb?sslmode=disable&max_conns=20&max_idle_conns=4
      - LOG_LEVEL=debug
    volumes:
      - ./kratos:/etc/config/kratos
    command: -c /etc/config/kratos/kratos.yml migrate sql -e --yes
    restart: on-failure
    networks:
      - intranet

  kratos:
    depends_on:
      - kratos-migrate
    image: oryd/kratos:v1.1.0
    ports:
      - '4433:4433' # public
      - '4434:4434' # admin
    restart: unless-stopped
    environment:
      - DSN=cockroach://root@cockroachdb:26257/defaultdb?sslmode=disable&max_conns=20&max_idle_conns=4
      - SERVE_PUBLIC_BASE_URL=http://127.0.0.1:4455/.ory/kratos/public/
      - LOG_LEVEL=debug
    command: serve -c /etc/config/kratos/kratos.yml --dev --watch-courier --sqa-opt-out
    volumes:
      - ./kratos:/etc/config/kratos
    networks:
      - intranet

  mailslurper:
    image: oryd/mailslurper:latest-smtps
    ports:
      - '4436:4436'
      - '4437:4437'
    networks:
      - intranet

  cockroachdb:
    image: cockroachdb/cockroach:latest-v23.2
    command: start-single-node --insecure
    ports:
      # - '8080:8080'
      - '26257:26257'
    volumes:
      - cockroachdb-data:/cockroach/cockroach-data
    healthcheck:
      test: curl --fail http://localhost:8080/health?ready=1 || exit 1
      interval: 2s
      retries: 3
      start_period: 15s
      timeout: 5s
    networks:
      - intranet

networks:
  intranet:

volumes:
  cockroachdb-data:
